# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_auto_20160112_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Post',
        ),
    ]
